### ISSUE TITLE
Traefik - wildcard on kubernetes

### ISSUE THREAD

**Issue by arvelinger** [techno-tim/launchpad#21]
Hi Tim!

i have a problem with clusterIssuer. I can't manage why im still getting error like this:

> E1005 11:18:39.797876       1 controller.go:166] cert-manager/challenges "msg"="re-queuing item due to error processing" "error"="specified key \"API token from Cloudflare" not found in secret cert-manager/cloudflare-token-secret" "key"="default/local-mysite-name-gks9v-1493540579-3817414012"

My config is looking like this:

```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-token-secret
  namespace: cert-manager
type: Opaque
stringData:
  cloudflare-token: <API token Cloudflare >

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: mymail@mydomain.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          cloudflare:
            email: mymail@gmail.com
            apiTokenSecretRef:
              name: cloudflare-token-secret
              key: <API token Cloudflare>
        selector:
          dnsZones:
            - "mysitename.com"

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: mymail@gmail.com
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          cloudflare:
            email: mymail@gmail.com
            apiTokenSecretRef:
              name: cloudflare-token-secret
              key: <API token Cloudflare>
        selector:
          dnsZones:
            - "mysitename.com"

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-mysitename-staging-cloud
  namespace: default
spec:
  secretName: local-mysitename-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.local.mysitename.com"
  dnsNames:
  - "local.mysitename.com"
  - "*.local.mysitename.com"

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-mysitename
  namespace: default
spec:
  secretName: local-mysitename-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.local.mysitename.com"
  dnsNames:
  - "local.mysitename.com"
  - "*.local.mysitename.com"
```

**Comment by arvelinger** [comment]
Stupid me... :D 

Guys don't type your token here:
```yaml
    email: mymail@gmail.com
            apiTokenSecretRef:
              name: cloudflare-token-secret
              key: <API token Cloudflare>
```
i did that and was trying to figure out why its not working :D
