### ISSUE TITLE
Domain Port Forward

### ISSUE THREAD

**Issue by theobouwman** [techno-tim/launchpad#28]
I have my domain example.com pointed to my router. Should I port my ports 80 and 443 to the LoadBalancer IP:
```
service:
  enabled: true
  type: LoadBalancer
  annotations: {}
  labels: {}
  spec:
    loadBalancerIP: 192.168.178.89 # this should be an IP in the MetalLB range
  loadBalancerSourceRanges: []
  externalIPs: []
```

Because when I try to access treafik.example.com I get no result/
