### ISSUE TITLE
Etdc metrics are not being scraped

### ISSUE THREAD

**Issue by MichaelKora** [techno-tim/launchpad#65]
Hey @timothystewart6. I am using k8s on bare metal with talos... i was able to setup the dashboard with tutorial but the issue is, when i try to see etcd metrics it shows "`No Data`".  Ihonestly i dont know if its a Talos issue or something with my grafana config. any idea where the issue may lie ?
thanks

i updated this section with the IPs of my cluster's control planes

```yaml
kubeEtcd:
  enabled: true
  endpoints: 
    # ips of the controle planes of my cluster
    - xx.xx.xx.xxx
    - yy.yy.yy.yyy
    - zz.zz.zz.zzz
  service:
    enabled: true
    port: 2379
    targetPort: 2379
    # on talos etcd uses port 2379 for client communication and port 2380 for peer communication in a cluster
```
