### ISSUE TITLE
Traefik using tls secret from traefik namespace instead of default

### ISSUE THREAD

**Issue by chakraborty29** [techno-tim/launchpad#79]
As per the [documentation](https://technotim.live/posts/kube-traefik-cert-manager-le/), the cert-manager certificate is created in the default namespace. However, I am currently running into an issue where Traefik is referring to its own namespace for the secret, when it's in the default namespace. 

Error:
```
Error configuring TLS error="secret traefik/stage-example-tls does not exist" ingress=traefik-dashboard namespace=traefik providerName=kubernetescrd
```

Is there a workaround to allow Traefik to use the default namespace when pulling the certificates? Or have I missed something from the video or documentation?

**Comment by chakraborty29** [comment]
Looks like it was by design that you cannot access secrets from one namespace to another: https://github.com/traefik/traefik/issues/5736#issuecomment-546981482

This becomes a headache when dealing with wildcard certificates. Looking into other solutions that does not require to duplicate certificates across namespaces, which can get messy when refreshing cert on expiry

**Comment by timothystewart6** [comment]
@chakraborty29   I use Reflector.  I know you said you don't want to use something that did this, but this is the exact use case.  My docs even show how to do it with `cert-manager`.  

https://technotim.live/posts/k8s-reflector/

**Comment by chakraborty29** [comment]
@timothystewart6 Awesome! Good to know you already have documentation on this. I ended up coming to the same conclusion last night after some research and finding the same in the [cert-manager docs](https://cert-manager.io/docs/devops-tips/syncing-secrets-across-namespaces/#using-reflector).

My worry was about having to replicate the certs manually across namespaces and then having to do the same when they are renewed, but Reflector takes care of the problem and works great.

**Comment by casudo** [comment]
@timothystewart6 How are you referencing the replicated secret via Reflector in your IngressRoute.yaml for Traefik?

I was able to mirror my certificate from the "cert-manager" namespace into my "longhorn-system" namespace, but adding the following to my nginx-ingressroute.yaml didn't work, since Traefik still used it's own certificate:
```yaml
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata: 
  name: longhorn-web-gui
  namespace: longhorn-system
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`longhorn.my.local.domain`)
      kind: Rule
      services:
        - name: longhorn-frontend
          port: 80
  tls:
    secretName: mylocaldomain-wildcard-certificate-secret
```

Any help would be appreciated. :-)
